from common import utility as u


class writer:

    def __init__(self, rel_path, generate_header=True, comment_prefix='//', using_tab=False):
        self.path = rel_path
        self.indent = 0
        self.content = []
        self.using_tab = using_tab
        if generate_header:
            self.wl(comment_prefix + ' THIS FILE IS AUTOMATIC GENERATED BY REFLECT TOOL')            
            self.wl(comment_prefix + ' DO NOT MODIFY THIS FILE MANUALLY')
            self.wl()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        self.flush()

    def w(self, txt='', indent=0):
        if indent < 0:
            self.indent += indent
        if self.using_tab:
            self.content.append('\t' * (self.indent / 4) + str(txt))
        else:
            self.content.append(' ' * self.indent + str(txt))
        if indent > 0:
            self.indent += indent

    def wl(self, txt='', indent=0):
        self.w(str(txt) + '\n', indent)

    def wfl(self, txt='', *args):
        self.wl(str(txt).format(*args))

    def flush(self):
        if u.write(self.path, ''.join(self.content)):
            u.log('Reflect => ' + self.path)
